CREATE TABLE Zutat_Allergen (
    ZUTAT_ID        BIGINT      NOT NULL,
    ALLERGEN_ID        BIGINT      NOT NULL,

    CONSTRAINT PK_Zutat_Allergen PRIMARY KEY (ZUTAT_ID,ALLERGEN_ID),
    FOREIGN KEY (ZUTAT_ID) REFERENCES Zutat(ID) ON DELETE CASCADE,
    FOREIGN KEY (ALLERGEN_ID) REFERENCES Allergen(ID) ON DELETE CASCADE
);