CREATE TABLE Zutat_Rezept (
    ID                          BIGINT          NOT NULL AUTO_INCREMENT,
    ZUTAT_ID        BIGINT      NOT NULL,
    REZEPT_ID        BIGINT      NOT NULL,
    MENGE        BIGINT      NOT NULL,
    EINHEIT_ID        BIGINT      NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ZUTAT_ID) REFERENCES Zutat(ID) ON DELETE CASCADE,
    FOREIGN KEY (REZEPT_ID) REFERENCES Rezept(ID) ON DELETE CASCADE,
    FOREIGN KEY (EINHEIT_ID) REFERENCES Einheit(ID) ON DELETE CASCADE
    );