CREATE TABLE Rezept_Timer (
    TIMER_ID        FLOAT      NOT NULL,
    REZEPT_ID        BIGINT      NOT NULL,
    POSITION_TIMER        BIGINT      NOT NULL,

    CONSTRAINT PK_Rezept_Timer PRIMARY KEY (TIMER_ID,REZEPT_ID),
    FOREIGN KEY (TIMER_ID) REFERENCES Timer(ZEIT) ON DELETE CASCADE,
    FOREIGN KEY (REZEPT_ID) REFERENCES Rezept(ID) ON DELETE CASCADE
    );