insert into REZEPT (ID, ANWEISUNGEN, ZEIT, SCHWIERIGKEIT, DEFAULT_PORTIONEN, DURCHSCHNITTLICHE_BEWERTUNG, ZUTAT_ID, NAME)
VALUES ('5', 'unterrühren', '1', '2', '3', '3','1', 'Mamor Kuchen');
insert into REZEPT (ID, ANWEISUNGEN, ZEIT, SCHWIERIGKEIT, DEFAULT_PORTIONEN, DURCHSCHNITTLICHE_BEWERTUNG, ZUTAT_ID, NAME)
VALUES ('8', 'köcheln lassen', '30', '4', '3', '2','2', 'Spaghetti');
insert into REZEPT (ID, ANWEISUNGEN, ZEIT, SCHWIERIGKEIT, DEFAULT_PORTIONEN, DURCHSCHNITTLICHE_BEWERTUNG, ZUTAT_ID, NAME)
VALUES ('11', 'schneiden', '1', '15', '2', '3','3', 'Gemüse-Auflauf');
insert into REZEPT (ID, ANWEISUNGEN, ZEIT, SCHWIERIGKEIT, DEFAULT_PORTIONEN, DURCHSCHNITTLICHE_BEWERTUNG, ZUTAT_ID, NAME)
VALUES ('14', 'Butter schmelzen', '20', '2', '2', '3','4', 'Cookies');
