insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('Docmed123', 'haha123', 'docmed123@mail.de');
insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('Tobias Quix', 'quixtobtob', 'qui@berufskolleg-geilenkirchen.de');
insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('Sebastian', 'test', 'test@test.com');
insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('BananaBrother', 'banan4Ever', 'bananafever@fevertime.tv');
insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('John Helldiver', 'libertea&democracy', 'liber@tea.de');
insert into USERTABLE (USERNAME, PASSWORT, EMAIL_ADRESSE) VALUES ('PancakeLady13', 'i<3pancakes', 'lady@pancake.com');

UPDATE Rezept SET USER_ID = '1' WHERE ID = '1';
UPDATE Rezept SET USER_ID = '1' WHERE ID = '2';
UPDATE Rezept SET USER_ID = '1' WHERE ID = '3';
UPDATE Rezept SET USER_ID = '2' WHERE ID = '4';
UPDATE Rezept SET USER_ID = '2' WHERE ID = '5';
UPDATE Rezept SET USER_ID = '2' WHERE ID = '6';
UPDATE Rezept SET USER_ID = '2' WHERE ID = '7';
UPDATE Rezept SET USER_ID = '2' WHERE ID = '8';
UPDATE Rezept SET USER_ID = '3' WHERE ID = '9';
UPDATE Rezept SET USER_ID = '3' WHERE ID = '10';
UPDATE Rezept SET USER_ID = '4' WHERE ID = '11';
UPDATE Rezept SET USER_ID = '4' WHERE ID = '12';
UPDATE Rezept SET USER_ID = '5' WHERE ID = '13';
UPDATE Rezept SET USER_ID = '5' WHERE ID = '14';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '15';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '16';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '17';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '18';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '19';
UPDATE Rezept SET USER_ID = '6' WHERE ID = '20';